// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_xYrNX77cnqY1BvakVqQlKFTHNCXYgo',
    appId: '1:610092974568:web:a0ec38cafd66a99861e45d',
    messagingSenderId: '610092974568',
    projectId: 'daily-algo',
    authDomain: 'daily-algo.firebaseapp.com',
    storageBucket: 'daily-algo.appspot.com',
    measurementId: 'G-S4Q7ZZN4NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodcmW7oOFhOljzDm8MjpA6X8j6OXklSs',
    appId: '1:610092974568:android:4a2caf9105f49fb061e45d',
    messagingSenderId: '610092974568',
    projectId: 'daily-algo',
    storageBucket: 'daily-algo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxtrxRqoLvNpMBWvUuUMXiI8fQsH6rRK8',
    appId: '1:610092974568:ios:f3a8d0e7ede5ce2261e45d',
    messagingSenderId: '610092974568',
    projectId: 'daily-algo',
    storageBucket: 'daily-algo.appspot.com',
    iosBundleId: 'com.example.dailyAlgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxtrxRqoLvNpMBWvUuUMXiI8fQsH6rRK8',
    appId: '1:610092974568:ios:0e439652f01513e461e45d',
    messagingSenderId: '610092974568',
    projectId: 'daily-algo',
    storageBucket: 'daily-algo.appspot.com',
    iosBundleId: 'com.example.dailyAlgo.RunnerTests',
  );
}
